name = "TopoNoise"
uuid = "e4d92942-b8aa-4e68-9ea0-8f8172a401ff"
authors = ["yuqingrong"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
